path: C:\Users\\reddy\\Documents\\Projects\\Engagement Tracker\\engagement-tracker-python\\aug_data
train: images\train
val: images\val
test: images\test

## Classes
names:
    0: not_engaged
    1: engaged